### ISSUE TITLE
ModuleNotFoundError: No module named 'ghostscript', but ghostscript installed

### ISSUE THREAD

**Issue by halloleo** [py-pdf/pypdf_table_extraction#14]
When doing a lattice conversion I get the following error:

```
  File "/my/venv/path/lib/python3.8/site-packages/camelot/backends/ghostscript_backend.py", line 34, in convert
    import ghostscript
ModuleNotFoundError: No module named 'ghostscript'
```

**Steps to reproduce the bug**

*Steps used to install `camelot`*

1. `brew install ghostscript`
2. `git clone https://github.com/py-pdf/pypdf_table_extraction.git`
3. `pip install ".[base]"`
4. `pip install opencv-python`

*Steps to be used to reproduce behavior:*

1. Run
        camelot -f csv -o out.csv lattice in.pdf

**Expected behavior**

A atble in `out.csv`
**Environment**

- OS: [e.g. macOS] macOS Sonoma
- Python version: 3.8.18
- Camelot version: `pypdf-table-extraction` repo from 20 Mar 2024

**Additional context**

I checked in the Python REPL of the `pypdf-table-extraction` venv:

```
>>> from ctypes.util import find_library
>>> find_library("gs")
'/opt/homebrew/lib/libgs.dylib'
```

but

```
>>> import ghostscript
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'ghostscript'
```

**Comment by foarsitter** [comment]
`pip install ghostscript` will do the trick. `[tool.poetry.group.base.dependencies]` are not compatible with pip extras for what I known.

**Comment by halloleo** [comment]
This worked. thanks.
