### ISSUE TITLE
Broken Custom Backend after aa61d3a

### ISSUE THREAD

**Issue by snanda85** [py-pdf/pypdf_table_extraction#222]
The commit aa61d3a breaks custom backend functionality.

The following traceback is seen when a custom backend object is passed to read_pdf:

```
   ...
     yield from camelot.read_pdf(
                ^^^^^^^^^^^^^^^^^
   File "/opt/venv/lib/python3.12/site-packages/camelot/io.py", line 130, in read_pdf
     tables = p.parse(
              ^^^^^^^^
   File "/opt/venv/lib/python3.12/site-packages/camelot/handlers.py", line 217, in parse
     parser = parser_obj(debug=self.debug, **kwargs)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/venv/lib/python3.12/site-packages/camelot/parsers/lattice.py", line 123, in __init__
     self.icb = ImageConversionBackend(use_fallback=use_fallback, backend=backend)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/opt/venv/lib/python3.12/site-packages/camelot/backends/image_conversion.py", line 41, in __init__
     raise ValueError(f"Image conversion backend {backend!r} not supported")
```

This happens because the checks in Lattice.__get_backend wrapper are not present in ImageConversionBackend.__init__

I can raise a PR but it seems this would need a bit of refactor as well. We can either continue to use the __get_backend method enhance it to use fallback, or remove the wrapper altogether and move everything to ICB.__init__
@bosd your thoughts?

**Comment by bosd** [comment]
>  This happens because the checks in Lattice.__get_backend wrapper are not present in ImageConversionBackend.init

I can raise a PR but it seems this would need a bit of refactor as well. 

Good catch. It may indeed make more sense to move the checks from the `__get_backend` method to the ICB.
For example when someone would have the pr ready for ocr/ alternative image conversion.
