### ISSUE TITLE
The module does'nt display the correct vresion information (Correctly configure version bump plugin)

### ISSUE THREAD

**Issue by bosd** [py-pdf/pypdf_table_extraction#259]
**Describe the bug**

The pypdf_table_extraction version info from the cli / library, does'nt match the pypi version.
(or toml file)

**Steps to reproduce the bug**

install this library from source or pypi.
run `pypdf_table_extraction --version`

result: `Using pypdf_table_extraction v0.0.1 `

But in this case, we are actually using v0.0.2.
Which is the correct version is stated in the toml file.

**Expected behavior**

Display the correct version info.

**Additional context**

The CLi reads it version information from:

So we want to write the version information to that file.

I'have found this poetry plugin which would allow to do so.
https://pypi.org/project/poetry-bumpversion/
The desired state, is when on gh actions a release is triggered. The correct version info is written to the version file.

The toml file reads.
https://github.com/py-pdf/pypdf_table_extraction/blob/58a831726b67f80c1cbdbea4f410d710576bf02c/pyproject.toml#L89

But appearantly on the 0.02 release, the version was not updated.
https://github.com/py-pdf/pypdf_table_extraction/blob/58a831726b67f80c1cbdbea4f410d710576bf02c/camelot/__version__.py#L1

It appears the plugin is not setup correctly.

**Comment by bosd** [comment]
Thanks. Did you manage to install the plugin? I'm getting an error when trying to install it.
( It cannot be defined in the toml file as a dependency.)

**Comment by bosd** [comment]
> Yes, the command `poetry self add poetry-bumpversion` worked for me to install the plugin.

Did it actually write something in the toml file? 
I don't see that in the diff on the pr.

**Comment by snanda85** [comment]
No it did not write anything in the toml or lock files.. just installed the
plugin.
