### ISSUE TITLE
Enable Codecov on this repo

### ISSUE THREAD

**Issue by bosd** [py-pdf/pypdf_table_extraction#29]
**Describe the bug**

Visiting https://app.codecov.io/github/py-pdf shows an inactive status for this repo.

**Expected behavior**
Code coverage available on the web, as well as running on PR's.

**Environment**

gh actions

@foarsitter , @MartinThoma Can you fix the codecov implementation?

**Comment by foarsitter** [comment]
I don't have the permissions for that.

**Comment by bosd** [comment]
@MartinThoma Can you help?

**Comment by MasterOdin** [comment]
It looks like CodeCov was enabled for the repo (https://app.codecov.io/gh/py-pdf/pypdf_table_extraction), but that we need to update this:

https://github.com/py-pdf/pypdf_table_extraction/blob/a5857c5c6f27b4e602b42ff5f61cfad077f58e47/.github/workflows/tests.yml#L168-L169

to use `codecov/codecov-action@4` and pass in a configuration token so it can upload the coverage data (or else hit rate limits). @bosd if you have edit access to the repo's settings, drop me a line at my email (in profile) and I can send you the token to plug in as a [GitHub actions secret](https://docs.github.com/en/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions) and can get this wired up.

**Comment by bosd** [comment]
> if you have edit access to the repo's settings

Thanks for your reply!! Actually , I don't have actions to the repo settings.
