### ISSUE TITLE
License Imprecision

### ISSUE THREAD

**Issue by JorjMcKie** [py-pdf/pypdf_table_extraction#312]
**Bug Description**

The license information is incomplete / incorrect:
The explicitly mentioned dependency on Ghostscript contradicts the classification of this package as "MIT License".
It should be explained under which conditions the package can be used.
In any case, Ghostscript **_cannot_** be used under an MIT License. Possible only are either GNU AGPL 3.0 or a commercial license.

**Comment by bosd** [comment]
I'm not a lawyer, But this question has come up a lot of times.
Most recent discussion is over here https://github.com/py-pdf/pypdf_table_extraction/issues/89#issuecomment-2325275040

We where on the edge of removing ghostscript completely. But as to some explanations and liks over in that treath. AGPL can we used when calling from an MIT program.
For those who think it is an problem Ghostscript dependency is optional ;)

Please join the discussion there. If you think more clarification is needed.
Or the conclusions drawn there are wrong.

Closing this one.
